app/src/main/java/com/door43/translationstudio/newui/translate/ChunkModeAdapter.java

I cannot build this develop branch as is.  To review the change in a build-able format see https://github.com/unfoldingWord-dev/ts-android/compare/master...PhotoNomad0:fix_854
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/915)

Fix 854 - deselect text on switch from target to source views

---

app/src/main/java/com/door43/translationstudio/newui/translate/ChunkModeAdapter.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/930)

Fix issue 926: Only accept card clicks outside EditText when editable.

---

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java

The reported bad behavior (being able to drop a verse marker in a
different frame) was observable because frames would keep listening
for drags after their drag events ended, even though a new listener
was being created for every new drag. By killing the listener when
the drag is done, only a marker's source is a valid target for a
drop.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/932)

Fix issue #826: Make views stop listening when drags end.

---

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java

Fix #1005 - make keyboard close when users mark the focused frame as done.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1020)

 Fix #1005 - make keyboard close when users mark the focused frame as done. 

---

app/src/main/java/com/door43/translationstudio/newui/translate/ReadModeAdapter.java

Fix issue #966 - the title of the target translation card in the read mode needs to use the translated title
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1025)

Fix issue #966 - the title of the target translation card in the read mode needs to use the translated title

---

app/src/main/res/layout/activity_terms.xml

Fix issue #990 add horizontal lines between terms of use buttons
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1040)

Fix issue #990 add horizontal lines between terms of use buttons

---

app/src/main/java/com/door43/translationstudio/dialogs/CustomAlertDialog.java

Fix Issue #776 - Custom Alert Dialog
Here is a small fix to the Custom Alert Dialog.  It currently shows a title of "Title" if the title is not set.
This fix will hide the title if not set.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1131)

Fix Issue #776 - Custom Alert Dialog - Hide Title if not set.

---

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java

Fix issue #1222 Problem with verse mark order checking in review mode.  
Make sure to capture verse marker changes when not in edit mode and before verifying chunk.
@neutrinog - looks like this is working right.  But you may want to review this fix.

Fix issue #1222 Problem with verse mark order checking in review mode

---

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeFragment.java

Fix issue #1232 where chapter ID is null.
@neutrinog - seems like this should work, but I don't know where there is a passage link to test this fix.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1236)

Fix issue #1232 where chapter ID is null

---

app/src/main/java/com/door43/translationstudio/tasks/UpdateAppTask.java

Fixes #1400 .
- Target translations are migrated every time the app starts instead of just when there is an update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1401)

target translations are now migrated every time the app runs

---

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java

Fix #1360 do not allow adding footnotes to Bible titles and references
This also includes "Fix #1359 do not allow footnotes in obs" otherwise would have a merge conflict.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1391)

Fix #1360 do not allow adding footnotes to Bible titles and references

---

app/src/main/java/com/door43/translationstudio/newui/translate/ChunkModeAdapter.java
app/src/main/java/com/door43/translationstudio/newui/translate/ReadModeAdapter.java

Fix #1371- verse markers are not rendered in the target translation while in read mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1393)

Fix #1371- verse markers are not rendered in the target translation while in read mode

---

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java
app/src/main/java/com/door43/translationstudio/tasks/ValidationTask.java

Fix #1196 chapter titles, references, and project titles need to be validated during the publishing process.
Added titles and references to the ValidationTask.  Modified ReviewModeAdapter so that if matching frame slug is not found, it defaults starting position to first card in chapter.  This allows us to scroll to show chapter title and references.

Fix #1196 chapter titles, references, and project titles need to be validated during the publishing process

---

app/src/main/java/com/door43/translationstudio/rendering/USFMRenderer.java
app/src/main/java/com/door43/translationstudio/rendering/USXRenderer.java

Fixes #1473 Formatting being lost.
Took out section of code that is removing linefeeds for both USX and USFM renderers.
@neutrinog - this seems to fix the linefeeds being stripped out.  Did you have more in mind?

Fixes #1473 Formatting being lost.

---

app/src/main/java/com/door43/translationstudio/core/Translator.java
app/src/main/java/com/door43/translationstudio/newui/home/HomeActivity.java
app/src/main/java/com/door43/translationstudio/tasks/ExamineImportsForCollisionsTask.java
app/src/main/java/com/door43/translationstudio/tasks/ImportProjectsTask.java
app/src/main/res/values/strings.xml

Fix #355 associate tstudio with app.
@neutrinog - ready for review.
Here are the results of testing app association with tstudio file on the 4 devices I have:
ES File Explorer - works with all the devices I have.
Google does not provide a file manager with Android.  Each manufacturer may or may not provide their own: http://www.howtogeek.com/202644/how-to-manage-files-and-use-the-file-system-on-android/
Because of this I suspect we will see a variety of behaviors on devices.  What I saw:
- Lenovo TAB 2 - works with built-in file-manager
- NeuTab N7 Pro - KitKat 4.4.2 - built in file manager  first prompts asking the type of the file.  It gives choices of text, image, audio, or video.  I selected image and then it gave choice of apps including tstudio.  Can then launch the app.
- Asus …

Fix #355 associate tstudio with app

---

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java
app/src/main/java/com/door43/translationstudio/rendering/USFMRenderer.java
app/src/main/res/values/strings.xml

Fixes #1457 type in verse markers while typing.
- Fix issue with dragging verse markers. Now when verse marker is dragged off screen and positioned to beginning, then change is now saved.
- Change to not hide duplicate or out of range verses. Will allow user to manually clean up.
- Expand onConfirmChunk() to handle USFM verse markers and do verse range checking.
@neutrinog - ready for review.

Fix #1457 type in verse markers while typing

---

app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java
app/src/main/res/values/strings.xml

Fix #1477 add attribution content when printing projects
Fixed unicode fonts for printing foreign symbols.
Extended PDF printer to convert basic html to PDF chunks and paragraphs.
@neutrinog

Fix #1477 add attribution content when printing projects

---

app/src/main/res/values/strings.xml

Fixes #1478 Add attribution to the settings page.
Updated License Agreement Text to match as close as possible the text and formatting.  This is limited by the subset of html supported in Android.
@neutrinog - please take a look to see if I understood this properly.

Fix #1478 Add attribution to the settings page

---

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java

Fix #1427 should not be able to place verse markers inside word .
- on drop of verse marker, if marker isn't in whitespace, then it is moved to closest whitespace.  It is biased toward whitespace before (start of word).

Fix #1427 should not be able to place verse markers inside word

---

app/src/main/java/com/door43/translationstudio/core/Library.java
app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java
app/src/main/java/com/door43/translationstudio/newui/PrintDialog.java

Fix #1578 images are not printed even though requested.
- Modified hasImages() so partially downloaded zip is not considered an image. 
- Fixed path for images in PdfPrinter.addContent(). Removed 360px from path since the subfolder is not created.
- Now saves a copy of PDF file to downloads folder in case send fails (such as file too large to email).

Fix 1578 images are not printed even though requested

---

app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java
app/src/main/res/values/strings.xml

Fix #1477 Add attribution of artwork to pdf output when images are printed.
@neutrinog - quick fix.

Fix #1477 Add attribution of artwork to pdf output.

---

app/src/main/java/com/door43/translationstudio/core/Library.java
app/src/main/java/com/door43/translationstudio/newui/translate/ChooseSourceTranslationAdapter.java
app/src/main/java/com/door43/translationstudio/newui/translate/ChooseSourceTranslationDialog.java
app/src/main/java/com/door43/translationstudio/tasks/DownloadSourceLanguageTask.java
app/src/main/res/layout/fragment_select_source_translation_list_download_item.xml
app/src/main/res/values/strings.xml

Fix #1563 app displays source translations before they are downloaded
- Could not reproduce the original issue, but made change to show all the sources for a project regardless of whether loaded or not.
- Sources that are not loaded show a download icon in place of checkbox.  When item is selected the user is warned that this will use the internet and must approve before proceeding.
- progress dialog is displayed during download.
- Draft sources are displayed with their checking level.
@neutrinog - please check to see if this approach is fine.

Fix #1563 app displays source translations before they are downloaded

---

app/src/main/java/com/door43/translationstudio/newui/home/HomeActivity.java
app/src/main/java/com/door43/translationstudio/newui/translate/ChooseSourceTranslationAdapter.java
app/src/main/java/com/door43/translationstudio/newui/translate/ChooseSourceTranslationDialog.java
app/src/main/java/com/door43/translationstudio/newui/translate/TargetTranslationActivity.java
app/src/main/res/layout/fragment_select_source_translation_list_updatable_item.xml
app/src/main/res/values/strings.xml

Fixes QA questions in #1563 app displays source translations before they are downloaded
- Added support for updating languages.
- Removed check for missing sources on project on HomeActivity since they can now be individually downloaded in source language chooser.
@neutrinog

Fix QA issues #1563 app displays source translations before they are downloaded

---

app/build.gradle
app/src/main/java/com/door43/translationstudio/App.java
app/src/main/java/com/door43/translationstudio/CrashReporterActivity.java
app/src/main/java/com/door43/translationstudio/newui/FeedbackDialog.java
app/src/main/java/com/door43/translationstudio/tasks/UploadBugReportTask.java
app/src/main/java/com/door43/translationstudio/tasks/UploadCrashReportTask.java
app/src/main/res/values/strings.xml

Fix #1608 cannot send feedback
- Updated logger to 2.0.0 which fixes https upload error and adds detection of response codes.
- Added capture and checking of upload report error codes in UploadBugReportTask and UploadCrashReportTask.   
- Fixed detection of crash reports.  
- Added detection of upload failed for crash reports and feedback.  Failures now have popup dialog shown to user.
@neutrinog - ready for review.

Fix #1608 cannot send feedback

---

app/src/main/java/com/door43/translationstudio/newui/BackupDialog.java
app/src/main/res/layout/dialog_backup.xml

Fix #1615 Remove the "Export USFM to SD Card" for OBS projects 
- Remove the "Export USFM to SD Card" backup option for OBS projects 
@neutrinog - ready for review.

Fix #1615 Remove the "Export USFM to SD Card" for OBS projects 

---

app/src/main/java/com/door43/translationstudio/SettingsActivity.java
app/src/main/java/com/door43/translationstudio/core/Typography.java
app/src/main/java/com/door43/translationstudio/newui/draft/DraftAdapter.java
app/src/main/java/com/door43/translationstudio/newui/library/ServerLibraryDetailFragment.java
app/src/main/java/com/door43/translationstudio/newui/library/ServerLibraryLanguageAdapter.java
app/src/main/java/com/door43/translationstudio/newui/publish/ValidationAdapter.java
app/src/main/java/com/door43/translationstudio/newui/translate/ChunkModeAdapter.java
app/src/main/java/com/door43/translationstudio/newui/translate/ReadModeAdapter.java
app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java
app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeFragment.java
app/src/main/java/com/door43/translationstudio/tasks/PrintPDFTask.java
app/src/main/res/values/strings_user_pref.xml
app/src/main/res/xml/general_preferences.xml

Fix #1549 provide font settings for source translation and target translation.
- Expanded Preferences to include both source and translation font settings. 
- Changed Typography to include a selector for either source or target.

Fix #1549 provide font settings for source translation and target translation

---

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java

Fix #1588 fix done toggle
- 	ReviewModeAdapter - fix for setting item.isComplete state on done toggle.
@neutrinog - it looks like the problem was with a new isComplete flag that was getting changed with toggle button - so card was getting redrawn back to initial state.

Fix #1588 fix done toggle

---

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java

Fix #1588 Fix issues with async rendering combined with filters
- ReviewModeAdapter - Changed from saving position to saving item in ViewHolder. Moved checking for task cancelled and holder changed into the runnable. This is to make certain that things haven't changed while runnable was queued. 
- ReviewModeAdapter - Replaced direct calls to notifyDataSetChanged() with triggerNotifyDataSetChanged().
@neutrinog - this seems to make things work with merge conflicts filters.

Fix #1588 Fix issues with async rendering combined with filters

---

app/src/main/java/com/door43/translationstudio/ui/translate/FirstTabFragment.java

Fix #1676 crash when project not found.
- FirstTabFragment - fix crash when mLibrary.index().getProject() returns null.
@neutrinog - not sure if this is the best way to fix this issue.

Fix #1676 crash when project not found.

---

app/src/main/java/com/door43/translationstudio/ui/LoginDoor43Activity.java

Fix #1547 Wrong error message when trying to log into Door43.
- Added check for network connectivity before showing login error.
@neutrinog - for review

Fix #1547 Wrong error message when trying to log into Door43.

---

app/src/main/java/com/door43/translationstudio/ui/dialogs/BackupDialog.java

Fix #1527 Enhance error dialog when upload fails
- BackupDialog: Added alert dialog if upload failed and we have lost internet connection.
- BackupDialog: backup to cloud button now shows no internet connection dialog instead of snack.  Snack would be hidden behind dialog on smaller screens.
@neutrinog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1748)

Fix #1527 Enhance error dialog when upload fails

---

app/src/main/res/layout/fragment_target_translation_list_item.xml

Fix #1424 Long Language names overflow the language column on the projects screens
- 	fragment_target_translation_list_item - Changed language side to use RelativeLayout to prevent overlapping language name on progress and info icons.
@neutrinog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1749)

Fix #1424 Long Language names overflow the language column on the projects screens

---

app/build.gradle
app/src/androidTest/java/com/door43/translationstudio/core/ExportUsfmTest.java
app/src/main/java/com/door43/translationstudio/core/DownloadImages.java
app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java
app/src/main/java/com/door43/translationstudio/core/Translator.java
app/src/main/java/com/door43/translationstudio/tasks/DownloadImagesTask.java
app/src/main/java/com/door43/translationstudio/tasks/PrintPDFTask.java
app/src/main/java/com/door43/translationstudio/ui/dialogs/PrintDialog.java

Fix #1246 fix image download
- Restored old Download Images code from older version
- DownloadImagesTask now returns the folder for images.  That folder is now passed into PdfPrinter. PdfPrinter corrected translation format for OBS.
- PrintDialog - fix output when regular folder is selected (not on SD card).
- Upgraded task-manager to 1.5.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1751)

Fix #1246 fix image download

---

app/src/main/java/com/door43/translationstudio/core/TargetTranslationMigrator.java

Fix v3 migration
- migrateChunkChanges now looks for project slug in manifest and then finds first "book" resource for chapter list.
@neutrinog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1755)

Fix v3 migration

---

app/src/main/java/com/door43/translationstudio/core/TargetTranslationMigrator.java
app/src/main/java/com/door43/translationstudio/core/Translator.java
app/src/main/java/com/door43/translationstudio/rendering/ClickableRenderingEngine.java
app/src/main/java/com/door43/translationstudio/rendering/RenderingGroup.java
app/src/main/java/com/door43/translationstudio/rendering/USFMRenderer.java
app/src/main/java/com/door43/translationstudio/rendering/USXRenderer.java
app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java

Fix #1664 save missing verse markers
- changed render functions to save flag that missing verses were added.
- in review mode adapter added flag to ReviewListItem for missing verses added.  When render has completed we check if missing verses were added.  If so, then we apply changes and trigger a new render.
- in Translator, added compileTranslationSpanned() to compile SpannedString.
- Fixed crash when undo moves back before a chunk file existed. There was an unhandled exception from core.  ReviewListItem nows captures that exception and gracefully recovers by replacing content with empty string.
@neutrinog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Fix #1664 save missing verse markers

---

app/src/main/java/com/door43/translationstudio/ui/dialogs/PrintDialog.java
app/src/main/res/values/strings.xml

Fix #1505 QA fail - remove second save
- Removed pdf chooser at end of Print.  
- Added print success dialog that displays path to file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1784)

Fix #1505 QA fail - remove second save

---

app/src/main/java/com/door43/translationstudio/ui/home/TargetTranslationAdapter.java
app/src/main/java/com/door43/translationstudio/ui/home/TargetTranslationListFragment.java

Fix #1593 persist sort options on home page
- Preserve last sort options on home page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1785)

Fix #1593 QA fail - persist sort options on home page

---

app/src/main/res/layout/dialog_update_library.xml

Fix #1690 QA fail - change text on update dialog
- Remove redundant warning of download times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1786)

Fix #1690 QA fail - change text on update dialog

---

app/src/main/java/com/door43/translationstudio/ui/dialogs/DownloadSourcesDialog.java
app/src/main/java/com/door43/translationstudio/ui/home/HomeActivity.java

Fix #1689 QA Fail - add cancel download source
- Fixed flawed logic that caused nothing to be shown with Download was cancelled.  Worked on logic to distinguish between  dialog being closed and download being cancelled.
- Fixed issue that sometimes on rotation the Update dialog would be on top.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1790)

Fix #1689 QA Fail - add cancel download source

---

app/src/main/java/com/door43/translationstudio/core/MergeConflictsHandler.java
app/src/main/java/com/door43/translationstudio/ui/dialogs/BackupDialog.java
app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java
app/src/main/res/values/strings.xml

Fix #1605 uploading with merge conflict
- Fixed issue that MergeConflictsHandler task was not starting.  
- Fixed bug with getting projectID.  
- Fixed issue that merge conflicts were not being redrawn when upload was done while editing translation.  Worked better calling onResume() of fragment than notify data changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1795)

Fix #1605 QA Fail - uploading with merge conflict

---

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java

Fix #1652 QA fail fix search navigation
- ReviewModeAdapter - removed special highlighting on current selected search item.  It was useful when we did search like everyone else, but now that we move by chunks...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1817)

Fix #1652 QA fail fix search navigation

---

app/src/main/java/com/door43/translationstudio/ui/translate/ListItem.java
app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java

Fix #1664 QA fail - verse markers not saved after drag.
- ListItem - created separate method for just reloading target from file to be called after edit was made to chunk.  Previously would just call load(), but that would only do something if source was null.  The new loadTarget() method will always reload target text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1838)

Fix #1664 QA fail - verse markers not saved after drag.

---

app/src/main/java/com/door43/translationstudio/core/DownloadImages.java
app/src/main/java/com/door43/translationstudio/tasks/DownloadImagesTask.java
app/src/main/res/values/strings.xml

Fix #1505 QA fail - Download Images for OBS printing appears hung after download
- DownloadImages: added more detail to progress.  Now shows unzipping progress so that user doesn't think app has hung after download.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1840)

Fix #1505 QA fail - Download Images for OBS printing appears hung after download

---

app/src/main/java/com/door43/translationstudio/tasks/DownloadResourceContainersTask.java
app/src/main/java/com/door43/translationstudio/ui/dialogs/DownloadSourcesDialog.java
app/src/main/res/values/strings.xml

Fix #1689 QA Fail - Only show source download success if helps also downloaded
- DownloadResourceContainersTask: changed to keep track of sources download with helps. If help fails, then mark everything as failed. Fix to show progress on first download. Add update of display when downloading helps.
- DownloadSourcesDialog: now shows successes and failures if complete source.  Source download is only successful if helps also downloads.  If error downloading helps then source download is considered download error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1847)

Fix #1689 QA Fail - Only show source download success if helps also downloaded

---

app/build.gradle
app/src/androidTest/java/com/door43/translationstudio/core/ExportUsfmTest.java
app/src/main/java/com/door43/translationstudio/core/ExportUsfm.java
app/src/main/java/com/door43/translationstudio/core/ImportUsfm.java
app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java

Fix #1827 Printing shows id tags if USFM import
Problem was that in USFM import, the USFM header tags were left in chapter front matter.  
- ImportUsfm: remove known USFM header tags from front matter.
- PdfPrinter: fix issue that no title is printed if title is not translated.  Now it will fall back to project name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1852)

Fix #1827 Printing shows id tags if USFM import

---

app/build.gradle
app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java

Fix #1667 save verse marker null crash
- Add check for null text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1853)

Fix #1667 - fix null text crash

---

app/src/main/java/com/door43/translationstudio/ui/devtools/DeveloperToolsActivity.java
app/src/main/java/com/door43/translationstudio/ui/dialogs/BackupDialog.java
app/src/main/java/com/door43/util/SdUtils.java
app/src/main/res/values/strings.xml

Fix #1637 QA fail - Cannot export to SD card
Also fixes formatting issue in #1638
- SdUtils - added capture of exception if sd card access permissions are not granted. Added capture of exception if we don't have permission in searching for files.
- DeveloperToolsActivity - added option to reset SD card access.
- Fixed formatting of SD card access prompt (new alert dialog does not work with spannable strings from html).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1868)

Fix #1637 QA fail - Cannot export to SD card

---

app/src/main/java/com/door43/translationstudio/ui/dialogs/BackupDialog.java
app/src/main/res/values/strings.xml

Fix #1777 fix upload verbiage to be more consistent with desktop
Also fixes #1850 backup verbiage.
- Upload dialog - changed verbiage to be more consistent with desktop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1870)

Fix #1777 fix upload verbiage to be more consistent with desktop

---

app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java

Fix #1822 popup keyboard on search
- TargetTranslationActivity: now saves handle to search edit text.  Fixed issue that notification of data change was closing keyboard as soon as search bar is brought up.  Now we don't automatically close the keyboard if the search bar is up and the search edit text has focus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1866)

Fix #1822 QA fail - popup keyboard on search

---

app/src/main/java/com/door43/translationstudio/ui/filechooser/FileChooserAdapter.java

Fix #1765 remove custom formatting on project files in File Chooser
- remove custom formatting on project files in File Chooser
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1891)

Fix #1765 remove custom formatting on project files in File Chooser

---

app/src/main/java/com/door43/translationstudio/core/TargetTranslation.java
app/src/main/java/com/door43/translationstudio/ui/home/ImportFromDoor43Dialog.java
app/src/main/java/com/door43/translationstudio/ui/home/TranslationRepositoryAdapter.java
app/src/main/res/values/strings.xml

Fix #1824 disable selection of unsupported resources
- TargetTranslation - added method to get resource type from id
- ImportFromDoor43Dialog - added check to make sure item is supported before opening.
- TranslationRepositoryAdapter - added checking to see if resource is supported, and grey out 
- TranslationRepositoryAdapter - made filtering for supported text translations optional.
- Added warning to user that project may not be supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1905)

Fix #1824 disable selection of unsupported resources

---

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java

Fix #1809 target card corruption on done
- Fix issue that when user selects done on a chunk, but is not in edit mode; then recycled junk is read in from mTargetEditableBody.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1907)

Fix #1809 target card corruption on done

---

app/src/main/java/com/door43/translationstudio/ui/home/ImportFromDoor43Dialog.java

Fix #1824 QA fail fix verbiage on unsupported import dialog
- ImportFromDoor43Dialog - changed text on import confirmation dialog ok button to "import".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1913)

Fix #1824 QA fail fix verbiage on unsupported import dialog

---

app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java

Fix #1610 QA fail - highlight conflict icon when in conflict filter mode.  It's a bunch of smoke and mirrors - conflict review mode now appears to be a separate view mode according to behavior of the side bar icons.  But it is really still a filter setting of review mode.
- TargetTranslationActivity - changed appearance of conflict filter to look as if it is a separate view mode as requested.  When in conflict filter mode, only conflict button is highlighted and shown selected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1914)

Fix 1610 QA fail - highlight conflict icon when in conflict filter mode.

---

app/src/androidTest/java/com/door43/translationstudio/ui/ImportUsfmActivityUiTest.java

Fix ImportUsfmActivityUiTest unit test
- ImportUsfmActivityUiTest - cleanup of imports projects. Removal of magic numbers etc. to make it more maintainable.  Simplified checkForImportErrors() to make more flexible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1918)

Fix ImportUsfmActivityUiTest unit test

---

app/src/main/res/layout/fragment_publish_validation_list_item.xml
app/src/main/res/layout/fragment_questionnaire_boolean_question.xml
app/src/main/res/layout/fragment_questionnaire_text_question.xml

Fix #1898 large cards displayed
- Fixed layout for recycleview cards so that they wrap content rather than the height of the parent.  Fixed review cards and new questions cards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1919)

Fix #1898 large cards displayed

---

app/src/main/java/com/door43/translationstudio/tasks/DownloadResourceContainersTask.java
app/src/main/java/com/door43/translationstudio/ui/dialogs/DownloadSourcesAdapter.java
app/src/main/java/com/door43/translationstudio/ui/dialogs/DownloadSourcesDialog.java
app/src/main/res/values/strings.xml

Fix #1845 inconsistencies in TW downloads
- DownloadResourceContainersTask - Consolidated code for downloading helps. Added support for downloading translation words.
- DownloadSourcesDialog - Moved creation of ProgressDialog outside of progress update loop to simplify and hopefully reduce risk of errors.
- DownloadSourcesAdapter - fixes to completely restore state after orientation change.  Removed redundant mDownloadError list.
- DownloadSourcesDialog - fixes to reconnect to existing source download task.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1927)

Fix #1845 inconsistencies in TW downloads

---

app/build.gradle
app/src/main/java/com/door43/translationstudio/core/ExportUsfm.java
app/src/main/java/com/door43/translationstudio/tasks/ExportProjectTask.java
app/src/main/java/com/door43/translationstudio/ui/dialogs/BackupDialog.java
app/src/main/java/com/door43/util/SdUtils.java
app/src/main/res/values/strings.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Fix #1928 & #1764 warn on export overwrite
- ExportUsfm & ExportProjectTask - fix for SD Card file overwrite. 
- BackupDialog - export project no longer has time stamp prefix. On export to USFM and export project now prompts user if file already exists.
- upgraded Android Studio to 2.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1939)

Fix #1928 & #1764 warn on export overwrite

---

app/build.gradle
app/src/main/java/com/door43/translationstudio/core/ExportUsfm.java
app/src/main/java/com/door43/translationstudio/tasks/ExportProjectTask.java
app/src/main/java/com/door43/translationstudio/ui/dialogs/BackupDialog.java
app/src/main/java/com/door43/translationstudio/ui/dialogs/PrintDialog.java
app/src/main/java/com/door43/util/SdUtils.java
app/src/main/res/values/strings.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Fix #1929 overwrite warning on print
Also Includes fixes in PR #1939 
- PrintDialog - fix for SD Card file overwrite. Now prompts user if file already exists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1940)

Fix #1929 overwrite warning on print

---

app/build.gradle
app/src/main/java/com/door43/translationstudio/ui/dialogs/BackupDialog.java
app/src/main/java/com/door43/translationstudio/ui/dialogs/PrintDialog.java
app/src/main/java/com/door43/util/SdUtils.java
app/src/main/res/values/strings.xml

Fix #1764 add date and size to overwrite prompt
- BackupDialog & PrintDialog - added localized date and size to overwrite warning.
- SdUtils - added comments about how SD card access works.  Added routines to get file size and date in localized format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1948)

Fix #1764 add date and size to overwrite prompt

---

app/src/main/java/com/door43/translationstudio/ui/translate/ChooseSourceTranslationAdapter.java

Fix #1949 crash on selecting new source
- ChooseSourceTranslationAdapter - fix for null pointer error on source selection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1950)

Fix #1949 crash on selecting new source

---

app/src/main/java/com/door43/translationstudio/tasks/ValidationTask.java
app/src/main/java/com/door43/translationstudio/ui/publish/ValidationFragment.java
app/src/main/res/values/strings.xml

Fix #1932 extra cards in review
- ValidationTask - fixed double entry of title and reference cards.  Added additional tip text to group cards, titles, and references to help user differentiate them from chunks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1951)

Fix 1932 extra cards in review

---

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java
app/src/main/java/com/door43/translationstudio/ui/translate/ViewModeFragment.java

Fix #1961 scroll bar position when searching
- TargetTranslationActivity - make sure item count has changed before changing seekbar maximum in order to reduce seekbar thrashing, and also update progress proportionally on maximum change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1968)

Fix 1961 scroll bar position when searching

---

app/src/main/java/com/door43/translationstudio/ui/dialogs/DownloadSourcesDialog.java
app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java

Fix #1845 QA fail disable progressbar click off cancel on update sources
- DownloadSourcesDialog - download progress dialog is no longer cancellable by clicking off.
- DownloadSourcesDialog - fix issue that cancel dismisses progress dialog immediately even though actual download cancel may be a long time later. We pop the dialog back up until task is finished.  This lets the user know that the task is not done yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1977)

Fix #1845 QA fail disable progressbar click off cancel on update sources

---

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java
app/src/main/res/values/strings.xml

Fix #1980 change footnote title from Note to Footnote
- ReviewModeAdapter - changed footnote title from Note to Footnote.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1986)

Fix #1980 change footnote title from Note to Footnote

---

app/src/main/java/com/door43/translationstudio/ui/devtools/DeveloperToolsActivity.java
app/src/main/java/com/door43/translationstudio/ui/filechooser/FileChooserActivity.java
app/src/main/java/com/door43/translationstudio/ui/home/ImportDialog.java
app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java
app/src/main/java/com/door43/util/SdUtils.java
app/src/main/res/values/strings.xml

Fix #1638 QA fail - fix sd card prompt and Kitkat support
- Fixed error message where user does not select the root folder of the SD card, but some other location.
- Tweak formatting of SD card prompt.
- FileChooserActivity - fixed issue that in SD card prompt the formatting was getting stripped out.  Added special handling for KitKit. Since we can only read from SD cards, but not write. Added flag to enable read access only so that we can at least import from SD card.
- SdUtils - validateSdCardWriteAccess() - fixed bug that if we could find the real path to the SD Card, we would return error.  This is not actually a bug.  It is just an inconvenience if user is trying to match the path to file manager.
- FileChooserActivity - fix in case user has inserted a …

Fix #1638 QA fail - fix sd card prompt and Kitkat support

---

app/build.gradle
app/src/main/java/com/door43/translationstudio/ui/translate/ChooseSourceTranslationAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/ChooseSourceTranslationDialog.java

Fix #1979 disable source selection while checking for updates
- ChooseSourceTranslationDialog - changed to show loading dialog while sources being checked.  Kicks off check for update whenever user selects a language. Made progress dialog useful for loading as well as downloading.
- ChooseSourceTranslationAdapter - changed to check the language for updates as it was being added only if selected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1994)

Fix #1979 disable source selection while checking for updates

---

app/build.gradle
app/src/main/java/com/door43/translationstudio/ui/draft/DraftAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/ChunkModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/ReadModeAdapter.java
app/src/main/res/values/strings.xml

Fix #1980 QA fail - footnote title
- Fix QA fail of footnote title - now changed in read and chunk mode.  Fixed case of footnote text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1999)

Fix #1980 QA fail - footnote title

---

app/build.gradle
app/src/main/java/com/door43/translationstudio/core/ExportUsfm.java
app/src/main/java/com/door43/translationstudio/ui/devtools/DeveloperToolsActivity.java
app/src/main/java/com/door43/util/SdUtils.java

Fix #1998 QA fail - export empty translation to USFM shows error
- ExportUsfm - fixed USFM export where translation is empty - output file was not being created and throwing exception.  Removed left-over support for export zipped chapters.
- SdUtils - logging cleanup: changed so that we no longer throw exception when SD card access was reset.  Made logs confusing to read.  Instead we place informational log that this is intentional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2000)

Fix #1998 QA fail - export empty translation to USFM shows error

---

app/build.gradle
app/src/main/java/com/door43/translationstudio/ui/translate/review/ReviewHolder.java

Fix #1997 crash on merge conflict rendering in review mode
- ReviewHolder - fixed crash when merge conflict cards are rendered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2001)

Fix #1997 crash on merge conflict rendering in review mode

---

app/src/main/java/com/door43/translationstudio/tasks/DownloadResourceContainerTask.java

Fix #2004 download stuck
- DownloadResourceContainerTask - improved exception logging for later debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2009)

Fix #2004 download stuck

---

app/src/main/res/values/strings.xml

Fix #1638 fix SD card access verbiage
- Tweaks to verbiage on instructions to enable SD Card access.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2014)

Fix #1638 fix SD card access verbiage

---

app/src/main/java/com/door43/translationstudio/ui/ImportUsfmActivity.java
app/src/main/java/com/door43/translationstudio/ui/home/ImportDialog.java
app/src/main/java/com/door43/translationstudio/ui/home/ImportFromDoor43Dialog.java
app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java
app/src/main/java/com/door43/translationstudio/ui/translate/ViewModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/ViewModeFragment.java
app/src/main/res/values/strings.xml

Fix #1762 QA fail - change merge prompt
- Have merge/overwrite prompting looking closer to what was requested without doing a major rewrite.
- ImportDialog - Changed import dialog text.
- ImportUsfmActivity - Added dialog for merge/overwrite prompting.  Added support for import overwrite.
- ImportFromDoor43Dialog - Changed import dialog text.  Added progress dialog on import (after download).
- ReviewModeAdapter - Add option to show merge conflict summary. 
- TargetTranslationActivity - show merge conflict summary when merge conflict.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2030)

Fix #1762 QA fail - change merge prompt

---

app/src/main/java/com/door43/translationstudio/ui/filechooser/FileChooserActivity.java
app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java
app/src/main/res/values/strings.xml

Fix #2016 fix SD card access granted dialog
- TargetTranslationActivity - consolidated shared SD card results dialog into FileChooserActivity.
- FileChooserActivity - added unique dialog title when SD card access is granted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2032)

Fix #2016 fix SD card access granted dialog

---

app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java

Fix #2027 fix crash on KitKat.  This addresses one issue found, but not the issue Kos is seeing.
- TargetTranslationActivity - Fix exception thrown on KitKat trying to cast context to TargetTranslationActivity. Removed dead code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2034)

Fix #2027 fix crash on KitKat

---

app/src/main/java/com/door43/translationstudio/ui/dialogs/DownloadSourcesDialog.java
app/src/main/java/com/door43/translationstudio/ui/home/ImportFromDoor43Dialog.java

Fix #2037 import dialog small screen fix
- ImportFromDoor43Dialog - fix for small screen sizes - maximize dialog width on small screens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2039)

Fix #2037 import dialog small screen fix

---

app/src/main/java/com/door43/translationstudio/ui/translate/ChooseSourceTranslationDialog.java

Fix #2051 choose sources on small screen
- ChooseSourceTranslationDialog - Fix for small display.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2054)

Fix #2051 choose sources on small screen

---

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java

Fix #2056 wrong merge conflict mode indication on rotation
- TargetTranslationActivity - Fix to restore merge conflict mode on rotation.
- ReviewModeAdapter - Fix to keep merge conflict icons and internal flags in sync.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2061)

Fix #2056 wrong merge conflict mode indication on rotation

---

app/src/main/java/com/door43/translationstudio/ui/dialogs/DownloadSourcesDialog.java
app/src/main/res/values/strings.xml

Fix #2021 problems with rotating device while downloading sources
- DownloadSourcesDialog - removed cancel button when loading the initial sources list - this caused a lot of trouble if the user did this.  For download progress, changed cancel button to not auto dismiss dialog, and added a message that we are cancelling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2068)

Fix #2021 problems with rotating device while downloading sources

---

app/src/main/java/com/door43/translationstudio/App.java
app/src/main/java/com/door43/translationstudio/ui/home/ImportFromDoor43Dialog.java

Fix #2074 no search text with keyboard
- ImportFromDoor43Dialog - fixed closing keyboard from within dialog fragment since activity.getCurrentFocus() does not work within a fragment.
- App - added new closeKeyboard that works on view
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2075)

Fix #2074 no search text with keyboard

---

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java
app/src/main/java/com/door43/translationstudio/ui/translate/ViewModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/ViewModeFragment.java

Fix #2078 need 2 clicks on merge conflict
- TargetTranslationActivity, ReviewModeAdapter, etc. - fix to make sure we properly initialize the merge conflicts flag when switching from read and chunked modes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2081)

Fix #2078 need 2 clicks on merge conflict

---

app/build.gradle
app/src/main/java/com/door43/translationstudio/ui/translate/ChunkModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/ReadModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/ViewModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/review/ReviewHolder.java

Fix #1995 QA Fail - unrecognized characters on source language tabs.
- ChunkModeAdapter, ReadModeAdapter, ReviewModeAdapter, ReviewHolder - added font support to source language tabs.
- ViewModeAdapter - added shared code for source language tab support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2097)

Fix #1995 QA Fail - unrecognized characters on source language tabs.

---

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java
app/src/main/java/com/door43/translationstudio/ui/translate/ViewModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/ViewModeFragment.java

Fix #2121 merge conflict count always shows 0
- ReviewModeAdapter - Fixed race condition that was showing merge conflict summary before items were loaded.
- TargetTranslationActivity - save and restore display state of merge conflict summary on rotation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2140)

Fix #2121 merge conflict count always shows 0

---

app/src/androidTest/assets/usfm/php_usfm_missing_initial_and_final_vs.usfm
app/src/androidTest/java/com/door43/translationstudio/core/ImportUsfmTest.java
app/src/main/java/com/door43/translationstudio/core/ImportUsfm.java

Fix #2143 USFM import fails when final chapters missing
- ImportUsfm - Fixed the starting chapter number when processing missing chapters.  Off by 1 error.
- ImportUsfmTest - Added new test case from Kos.  Added checking of imported verse count and other minor fixes.  Testing is now more rigorous.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2148)

Fix #2143 USFM import fails when final chapters missing

---

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java
app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java

Fix #2121 QA fail merge results keeps popping up
- TargetTranslationActivity - onPause() update display state of merge conflict summary.  Prevents a cancelled merge conflict summary from popping up after file selection activity runs.
- ReviewModeAdapter - disabled cancelable on merge conflict summary dialog so display state will get updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2145)

Fix #2121 QA fail merge results keeps popping up

---

app/src/main/java/com/door43/translationstudio/tasks/CheckForMergeConflictsTask.java
app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java

Fix #2121 QA fail fix race condition with conflict summary
- ReviewModeAdapter - Fix race condition on some devices that conflict summary check is triggered on rotation before items loaded and finishes after items loaded.
- CheckForMergeConflictsTask - tweak to return original item list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2158)

Fix #2121 QA fail fix race condition with conflict summary

---

app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java

Fix #2169 RTL printing of references
- PdfPrinter - shrunk chapter titles in TOC.  Shifted down page numbers… in TOC.  Added space between text and image below it.  Fixed RTL printing of reference and location of it.  Made verse markers superscript again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2170)

Fix #2169 RTL printing of references

---

app/src/main/res/layout/dialog_print.xml

Fix #2171 print dialog with long titles
- Fix problem with title wrapping on print dialog pushing options off screen.  Add Ellipsis if over long.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2172)

Fix #2171 print dialog with long titles

---

app/src/main/java/com/door43/translationstudio/ui/dialogs/PrintDialog.java
app/src/main/java/com/door43/translationstudio/ui/home/TargetTranslationInfoDialog.java
app/src/main/res/layout/dialog_target_translation_info.xml

Fix #2162 info dialog small screens
- TargetTranslationInfoDialog - fix screen width on small screens.
- dialog_target_translation_info.xml - fix problem that long language names push change button off screen.
- PrintDialog - fix screen width on small screens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2175)

Fix #2162 info dialog small screens

---

app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java
app/src/main/java/com/door43/translationstudio/core/Translator.java
app/src/main/java/com/door43/translationstudio/tasks/PrintPDFTask.java

Fix #2180 make pdf font size track screen size selected
- PdfPrinter, Translator, PrintPDFTask - add target font size parameter for printing.
- PdfPrinter - Make font sizes proportional to selected target font size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2203)

Fix #2180 make pdf font size track screen size selected

---

app/src/main/java/com/door43/translationstudio/core/Translator.java
app/src/main/java/com/door43/translationstudio/tasks/ImportProjectFromUriTask.java
app/src/main/java/com/door43/translationstudio/ui/home/ImportDialog.java
app/src/main/java/com/door43/translationstudio/ui/home/ImportFromDoor43Dialog.java
app/src/main/res/values/strings.xml

Fix #2188 prompt before merge on import even if there is no merge conflict.
- ImportDialog, ImportFromDoor43Dialog - keep track of previous merge option selection (overwrite or merge) and if last merge had conflict. Now prompt user for import options if there was an existing project (not just on merge conflict).
- Translator.importArchive(), ImportProjectFromUriTask - now save flag if a project already existed before import.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2205)

Fix #2188 prompt before merge on import even if there is no merge conflict.

---

app/src/main/java/com/door43/translationstudio/ui/home/HomeActivity.java
app/src/main/java/com/door43/translationstudio/ui/home/ImportDialog.java
app/src/main/java/com/door43/translationstudio/ui/home/ImportFromDoor43Dialog.java
app/src/main/res/values/strings.xml

Fix #2188 fix to show import success on non-conflicted merge
- ImportFromDoor43Dialog, ImportDialog - fix to show import success when merge not conflicted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2210)

Fix #2188 fix to show import success on non-conflicted merge

---

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java

Fix #2222 crash on resolve conflict
- ReviewModeAdapter - trigger redraw of card when merge conflict is resolved so that card type is changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2225)

Fix #2222 crash on resolve conflict

---

app/src/main/java/com/door43/translationstudio/ui/dialogs/BackupDialog.java

Fix #2221 app exits after upload conflict
- BackupDialog - fix bug that home activity was being closed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2227)

Fix #2221 app exits after upload conflict

---

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java

Fix #2229 crash on resolve conflict
- ReviewModeAdapter - fix for resolving conflict when in merge conflict mode to remove item from filtered items list to prevent starting redraw of card while merge filter being recalculated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2234)

Fix #2229 crash on resolve conflict
