app/src/main/java/com/door43/translationstudio/newui/translate/ChunkModeAdapter.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/919)
=> Fix issue #916: Open keyboard when focusing from click on translation card

app/src/main/java/com/door43/translationstudio/rendering/USXRenderer.java
Please note comments in the issue about how this has been tested.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/922)
=> Fix issue #917: Support rendering "qr" styles

app/src/main/java/com/door43/translationstudio/newui/translate/TargetTranslationActivity.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/921)
=> Fix issue #861. Refactor mode icon highlight setting code.

app/src/main/java/com/door43/translationstudio/newui/translate/TargetTranslationActivity.java, app/src/main/res/layout/toolbar_translator_sidebar.xml
Switch highlight color from accent_material_dark to primary_dark. Make highlight fill sidebar.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/929)
=> Issue 861 refinements

app/src/main/java/com/door43/translationstudio/newui/newtranslation/ProjectListFragment.java, app/src/main/java/com/door43/translationstudio/newui/newtranslation/TargetLanguageListFragment.java, app/src/main/java/com/door43/translationstudio/newui/translate/ChooseSourceTranslationDialog.java, app/src/main/res/layout/fragment_language_list.xml, app/src/main/res/layout/fragment_project_list.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/936)
=> Fix #763: Add subtitles

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java, app/src/main/res/layout/fragment_review_list_item.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/941)
=> Fix #759: Show done/undone state with a checkbox in review mode.

app/src/main/java/com/door43/translationstudio/rendering/USXRenderer.java
Fixes italicization, over-indenting verse markers for poetry, and superfluous linebreaks between adjacent paragraphs.
However, does nothing for wrapping long lines.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/944)
=> Text styling for issue #760

app/src/main/java/com/door43/translationstudio/newui/translate/TargetTranslationActivity.java
Original regression was introduced in 197d06b4.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/946)
=> Fix #945: Don't crash when clicking mode icon for the active mode.

app/src/main/java/com/door43/translationstudio/newui/publish/ReviewFragment.java, app/src/main/res/layout/fragment_publish_review.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/949)
=> Fix issue #804: Add buttons to review terms from publishing review

app/src/main/java/com/door43/translationstudio/core/TargetTranslation.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/948)
=> Fix #947: Don't include .git in the directories to check for chunks

app/src/main/java/com/door43/translationstudio/newui/publish/ProfileFragment.java, app/src/main/res/values/strings.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/951)
=> Fix #909: Present a privacy notice on upload

app/src/main/java/com/door43/translationstudio/newui/translate/ChunkModeAdapter.java, app/src/main/java/com/door43/translationstudio/newui/translate/ChunkModeFragment.java, app/src/main/java/com/door43/translationstudio/newui/translate/ReadModeAdapter.java, app/src/main/java/com/door43/translationstudio/newui/translate/ReadModeFragment.java
Fix #1016: Change Swipe behaviour to toggle Source/Translation card in chunk view.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1019)
=> Fix #1016: Change Swipe behaviour to toggle Source/Translation card in chunk view.

app/src/main/java/com/door43/translationstudio/newui/publish/ProfileFragment.java
Fix Issue #975 - Pop Up Privacy Notice with "i" Icon
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1024)
=> Fix Issue #975 - Pop Up Privacy Notice with "i" Icon

app/src/main/java/com/door43/translationstudio/newui/translate/ReadModeAdapter.java, app/src/main/java/com/door43/translationstudio/rendering/USXRenderer.java, app/src/main/res/layout/fragment_read_list_item.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1022)
=> Fix #994: Adding major section heading rendering support.

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java, app/src/main/res/layout/activity_terms.xml, app/src/main/res/layout/fragment_review_list_item.xml, app/src/main/res/values/strings.xml
Changed from button to switch.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1041)
=> Fix Issue #983 - improved chunk done

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java, app/src/main/res/layout/fragment_review_list_item.xml, app/src/main/res/values/strings.xml
Reverts unfoldingWord-dev/ts-android#1041
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1094)
=> Revert "Fix Issue #983 - improved chunk done"

app/src/main/java/com/door43/translationstudio/rendering/USXRenderer.java
Fix Issue #1132 array index out of range error.
@neutrinog - it looks like this error is still in the latest code.  You said to ping you about this, so this is it....
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1136)
=> Fix Issue #1132 array index out of range error

app/src/main/java/com/door43/translationstudio/core/TargetTranslationMigrator.java, app/src/main/java/com/door43/translationstudio/newui/home/ImportDialog.java, app/src/main/java/com/door43/translationstudio/newui/home/RestoreFromCloudDialog.java, app/src/main/java/com/door43/translationstudio/newui/translate/FirstTabFragment.java, app/src/main/java/com/door43/translationstudio/service/ClientService.java, app/src/main/java/com/door43/translationstudio/tasks/UpdateAppTask.java
Fix issue #1195 merge extra translation chunks.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1202)
=> Fix issue #1195 merge extra translation chunks

app/src/main/java/com/door43/translationstudio/core/TargetTranslationMigrator.java
Fix #1195 issues with chunk merge:
* Merge invalid chunk with previous frame when possible.
* Add chunk markers in all merge cases.
* Clear invalid chunks during merge.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1210)
=> Fix #1195 issues with chunk merge.

app/src/main/java/com/door43/translationstudio/newui/translate/ReadModeAdapter.java, app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java, app/src/main/java/com/door43/translationstudio/rendering/USXRenderer.java, app/src/main/res/values/strings.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1213)
=> Fix issue #963: Validate verse marker ordering and position

app/src/main/java/com/door43/translationstudio/newui/translate/ViewModeFragment.java
Fix Issue #1177 scrolling crash
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1220)
=> Fix Issue #1177 scrolling crash

app/src/main/java/com/door43/translationstudio/core/Typography.java, app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeFragment.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1221)
=> Fix issue #1187: Set tA article text size

app/src/main/java/com/door43/translationstudio/core/ArchiveImporter.java, app/src/main/java/com/door43/translationstudio/core/TargetTranslation.java, app/src/main/java/com/door43/translationstudio/core/TargetTranslationMigrator.java, app/src/main/java/com/door43/translationstudio/core/Translator.java, app/src/main/java/com/door43/util/Manifest.java
Fix Issue #1035 merge manifests on import
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1224)
=> Fix Issue #1035 merge manifests on import

app/src/main/java/com/door43/translationstudio/ProfileActivity.java, app/src/main/java/com/door43/translationstudio/core/Profile.java, app/src/main/res/values/strings.xml
For issue #1000
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1227)
=> Require name and email during profile configuration on app startup.

app/src/main/java/com/door43/translationstudio/AppContext.java, app/src/main/java/com/door43/translationstudio/MainApplication.java, app/src/main/java/com/door43/translationstudio/SettingsActivity.java, app/src/main/java/com/door43/translationstudio/filebrowser/DocumentFileItem.java, app/src/main/java/com/door43/translationstudio/newui/home/HomeActivity.java, app/src/main/java/com/door43/translationstudio/newui/translate/ViewModeFragment.java, app/src/main/res/xml/general_preferences.xml
Fix Issue #754 - Remember My Place
On startup automatically open last project.
Last project is now saved.
@neutrinog - not much work to do here - you did all the hard work.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1229)
=> Fix Issue #754 - Remember My Place

app/src/main/java/com/door43/translationstudio/AppContext.java, app/src/main/java/com/door43/translationstudio/ProfileActivity.java, app/src/main/java/com/door43/translationstudio/SettingsActivity.java, app/src/main/java/com/door43/translationstudio/core/Profile.java, app/src/main/java/com/door43/translationstudio/newui/ProfileDialog.java, app/src/main/res/layout/dialog_profile.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/general_preferences.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1230)
=> Fix #1228: Add user profile preference.

app/src/androidTest/java/com/door43/translationstudio/fast/ExportTest.java, app/src/main/java/com/door43/translationstudio/core/TargetTranslation.java, app/src/main/java/com/door43/translationstudio/newui/BackupDialog.java, app/src/main/java/com/door43/translationstudio/newui/publish/ProfileFragment.java, app/src/main/java/com/door43/translationstudio/service/BackupService.java, app/src/main/java/com/door43/translationstudio/service/ServerService.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1231)
=> Fix #985: require at least one translation contributor before backing up.

app/src/main/AndroidManifest.xml, app/src/main/java/com/door43/translationstudio/AppContext.java, app/src/main/java/com/door43/translationstudio/core/Library.java, app/src/main/java/com/door43/translationstudio/core/SourceTranslation.java, app/src/main/java/com/door43/translationstudio/newui/BaseActivity.java, app/src/main/java/com/door43/translationstudio/newui/DraftPreviewActivity.java, app/src/main/java/com/door43/translationstudio/newui/DraftPreviewActivityFragment.java, app/src/main/java/com/door43/translationstudio/newui/home/HomeActivity.java, app/src/main/java/com/door43/translationstudio/newui/home/TargetTranslationAdapter.java, app/src/main/java/com/door43/translationstudio/newui/publish/PublishActivity.java, app/src/main/java/com/door43/translationstudio/newui/publish/PublishStepFragment.java, app/src/main/java/com/door43/translationstudio/newui/translate/FirstTabFragment.java, app/src/main/java/com/door43/translationstudio/newui/translate/PreviewModeAdapter.java, app/src/main/java/com/door43/translationstudio/newui/translate/PreviewModeFragment.java, app/src/main/java/com/door43/translationstudio/newui/translate/ReadModeAdapter.java, app/src/main/java/com/door43/translationstudio/newui/translate/TargetTranslationActivity.java, app/src/main/java/com/door43/translationstudio/newui/translate/ViewModeFragment.java, app/src/main/res/layout/activity_draft_preview.xml, app/src/main/res/layout/content_draft_preview.xml, app/src/main/res/layout/fragment_draft_preview.xml, app/src/main/res/layout/fragment_preview_list_item.xml, app/src/main/res/layout/fragment_target_translation_list_item.xml, app/src/main/res/menu/menu_draft_preview.xml, app/src/main/res/values/strings.xml
Fix for issue #895 allow edit of drafts
@neutrinog - have a first pass at the UI to preview draft.  If user approves overwrite, then it copies to target translated project title, resource title, chapter title, and chapter fragments.  It also resets the finished flags on the target and does a commit.  Testing limited to OBS since I couldn't find any Bible books to download when I tried to update library.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1233)
=> Fix for issue #895 allow edit of drafts

app/src/main/java/com/door43/translationstudio/core/Downloader.java, app/src/main/java/com/door43/translationstudio/core/Library.java, app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java, app/src/main/java/com/door43/translationstudio/core/Resource.java, app/src/main/java/com/door43/translationstudio/newui/PrintDialog.java, app/src/main/java/com/door43/translationstudio/tasks/DownloadImagesTask.java, app/src/main/res/values/strings.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1234)
=> #883: Download images when printing

app/build.gradle, app/src/main/assets/schema.sql, app/src/main/java/com/door43/translationstudio/AppContext.java, app/src/main/java/com/door43/translationstudio/DeveloperToolsActivity.java, app/src/main/java/com/door43/translationstudio/SplashScreenActivity.java, app/src/main/java/com/door43/translationstudio/core/Downloader.java, app/src/main/java/com/door43/translationstudio/core/Indexer.java, app/src/main/java/com/door43/translationstudio/core/IndexerSQLiteHelper.java, app/src/main/java/com/door43/translationstudio/core/Library.java, app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java, app/src/main/java/com/door43/translationstudio/core/Resource.java, app/src/main/java/com/door43/translationstudio/newui/BaseActivity.java, app/src/main/java/com/door43/translationstudio/newui/BaseFragment.java, app/src/main/java/com/door43/translationstudio/newui/PrintDialog.java, app/src/main/java/com/door43/translationstudio/newui/home/HomeActivity.java, app/src/main/java/com/door43/translationstudio/newui/library/ServerLibraryActivity.java, app/src/main/java/com/door43/translationstudio/newui/library/ServerLibraryDetailFragment.java, app/src/main/java/com/door43/translationstudio/newui/translate/TargetTranslationActivity.java, app/src/main/java/com/door43/translationstudio/tasks/DownloadAllProjectsTask.java, app/src/main/java/com/door43/translationstudio/tasks/DownloadImagesTask.java, app/src/main/java/com/door43/translationstudio/tasks/GetLibraryUpdatesTask.java, app/src/main/java/com/door43/translationstudio/tasks/PrintPDFTask.java, app/src/main/java/com/door43/translationstudio/tasks/UpdateAppTask.java, app/src/main/res/values/strings.xml
an improvement to the pull request https://github.com/unfoldingWord-dev/ts-android/pull/1234 based on the issue https://github.com/unfoldingWord-dev/ts-android/issues/883.
This also includes some fixes for the draft preview as well as bugs in the library.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1245)
=> Printing with Images

app/src/main/java/com/door43/translationstudio/core/LibraryUpdates.java
fixes #1098.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1267)
=> fixes issue #1098

app/src/main/AndroidManifest.xml, app/src/main/java/com/door43/translationstudio/newui/home/HomeActivity.java
=> stubbed out some code for #355

app/src/main/java/com/door43/translationstudio/core/TargetTranslation.java, app/src/main/java/com/door43/translationstudio/core/Translator.java, app/src/main/java/com/door43/translationstudio/newui/home/RestoreFromCloudDialog.java, app/src/main/java/com/door43/translationstudio/newui/newtranslation/NewTargetTranslationActivity.java, app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java, app/src/main/java/com/door43/translationstudio/rendering/MergeConflictRenderer.java, app/src/main/java/com/door43/translationstudio/service/BackupService.java, app/src/main/java/com/door43/translationstudio/spannables/MergeConflictSpan.java, app/src/main/java/com/door43/translationstudio/tasks/UpdateAppTask.java
This finishes #1255 in addition to fixing bug when deleting target translations. Imports are now merged using git so that translators will no longer clobber each other's work even if they happen to work on the same chunk.
=> Finishing Issue1255

app/src/main/java/com/door43/translationstudio/newui/NativeSpeakerDialog.java, app/src/main/res/layout/dialog_native_speaker.xml, app/src/main/res/values/strings.xml
Finished some things in #887 that were previously skipped.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1299)
=> added checkbox stating translator agrees to licenses

app/src/main/java/com/door43/translationstudio/core/IndexerSQLiteHelper.java, com.door43.tools.security/build.gradle
Fixes #1355 .
- made some updates to the sqlite helper. Not sure if this fixes the issue but we will see!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1386)
=> updated sqlite helper

app/src/main/java/com/door43/translationstudio/core/TargetTranslation.java
Tag repos to indicate when published #1350
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1395)
=> Tag repos to indicate when published #1350

app/src/main/assets/LICENSE.md, app/src/main/java/com/door43/translationstudio/core/TargetTranslation.java, app/src/main/java/com/door43/translationstudio/core/TargetTranslationMigrator.java
Fix #1309 to include license file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1397)
=> Fix #1309 include license file

.travis.yml
Fixes #1378.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1402)
=> testing travis config

app/src/main/java/com/door43/translationstudio/core/TargetTranslation.java, app/src/main/java/com/door43/translationstudio/newui/home/ImportDialog.java, app/src/main/java/com/door43/translationstudio/newui/translate/TargetTranslationActivity.java
Fix #1365 Source language not set on imported project.
@neutrinog - check if this is the best way to approach this.  In ImportDialog added applySourcesToProjects() to pull the source translations from the manifest and add them to the project.
In TargetTranslation added method getSourceTranslations() to get list of source slugs in manifest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1394)
=> Fix #1365 Source language not set on imported project

app/src/main/java/com/door43/translationstudio/newui/ShareWithPeerDialog.java, app/src/main/java/com/door43/util/RSAEncryption.java
Fixes #1398.
- added better error handling
- added support for regenerating keys if they cannot be loaded
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1411)
=> added some better error handling to key handling

app/build.gradle, app/src/main/java/com/door43/translationstudio/tasks/UpdateAppTask.java
Fixes #1422 .
- add a null check in the update task
=> Hotfix update bug

app/src/main/java/com/door43/translationstudio/newui/publish/PublishFragment.java, app/src/main/res/values/strings.xml
Fixes #1455
Added display of URL where user can see published data.
=> Provide feedback on publishing to user #1455

app/build.gradle, app/src/main/java/com/door43/translationstudio/newui/home/ImportDialog.java, app/src/main/java/com/door43/translationstudio/newui/home/ImportFromDoor43Dialog.java, app/src/main/java/com/door43/translationstudio/newui/home/RestoreFromCloudAdapter.java, app/src/main/java/com/door43/translationstudio/newui/home/RestoreFromDoor43Dialog.java, app/src/main/java/com/door43/translationstudio/tasks/AdvancedGogsRepoSearchTask.java, app/src/main/java/com/door43/translationstudio/tasks/GetUserRepositoriesTask.java, app/src/main/java/com/door43/translationstudio/tasks/LoginDoor43Task.java, app/src/main/java/com/door43/translationstudio/tasks/PullTargetTranslationTask.java, app/src/main/java/com/door43/translationstudio/tasks/SearchGogsRepositoriesTask.java, app/src/main/java/com/door43/translationstudio/tasks/SearchGogsUsersTask.java, app/src/main/java/com/door43/translationstudio/tasks/UpdateAppTask.java, app/src/main/res/layout/dialog_import.xml, app/src/main/res/layout/dialog_import_from_door43.xml, app/src/main/res/layout/dialog_restore_from_door43.xml, app/src/main/res/values/strings.xml
Fixes #1343 .
- Adds the ability to import target translations from other users on git.door43
=> import target translations from other users on git.door43

app/src/androidTest/assets/usfm/jude.no_chapter_or_verses.usfm, app/src/androidTest/assets/usfm/jude.no_verses.usfm, app/src/androidTest/java/com/door43/translationstudio/core/ImportUsfmTest.java, app/src/androidTest/java/com/door43/translationstudio/newui/ImportUsfmActivityUiTest.java, app/src/main/java/com/door43/translationstudio/core/ImportUsfm.java, app/src/main/java/com/door43/translationstudio/newui/ImportUsfmActivity.java
Fixes #1344 Import USFM Data
Change so that user cannot continue import if processing file failed.
Added more unit test cases with missing verses.
=> Fixes #1344 Import USFM Data

app/src/androidTest/assets/usfm/php_usfm_C3_out_of_order.usfm, app/src/androidTest/assets/usfm/php_usfm_DuplicateC2.usfm, app/src/androidTest/assets/usfm/php_usfm_NoC1.usfm, app/src/androidTest/assets/usfm/php_usfm_NoC2.usfm, app/src/androidTest/assets/usfm/php_usfm_missing_last_chapter.usfm, app/src/androidTest/java/com/door43/translationstudio/core/ImportUsfmTest.java, app/src/main/java/com/door43/translationstudio/core/ImportUsfm.java, app/src/main/res/values/strings.xml
#1344 Import USFM Data - Fix for out of order or missing chapters.  
Added chapter tracking and updated test cases.
@neutrinog - fix for QA fail.
=> #1344 Import USFM Data - Fix for out of order or missing chapters.  Updated test cases.

app/src/main/java/com/door43/translationstudio/CrashReporterActivity.java, app/src/main/java/com/door43/translationstudio/SettingsActivity.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/general_preferences.xml
Fixes #1116 - Add check for apk updates option in Settings.
=> Fixes #1116 - Add check for apk updates option in Settings.

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java
Fixes #1573 Fix drag exception.  Also Fixes #1574 drag exception.
- Fix drag exception by checking spanRange.
=> Fixes #1573 Fix drag exception.

app/build.gradle, app/src/main/java/com/door43/translationstudio/newui/BackupDialog.java, app/src/main/java/com/door43/translationstudio/newui/translate/ChooseSourceTranslationDialog.java, app/src/main/java/com/door43/translationstudio/tasks/PushTargetTranslationTask.java, build.gradle
Fixes #1604.
- added back the ability for users to view their uploaded translation online
- updated the url address
=> fixes #1604

app/src/main/res/layout/dialog_backup.xml
Fixes QA fail of #1584 Implement new upload/export/print workflow 
Fixed merge issue that left old button export USFM to SD on dialog.
=> Fixes QA fail of #1584 Implement new upload/export/print workflow 

app/src/main/java/com/door43/translationstudio/tasks/PushTargetTranslationTask.java
Fixes #1614 cannot upload or export project
- selects master branch before push.
=> Fix #1614 cannot upload or export project

app/src/main/java/com/door43/translationstudio/newui/BackupDialog.java
Fixes #1605 modify upload conflicting project dialog
-Just changed the text shown on the dialog.
=> Fix #1605 modify upload conflicting project dialog

app/src/main/java/com/door43/translationstudio/core/TargetTranslation.java, app/src/main/java/com/door43/translationstudio/core/Translator.java, app/src/main/java/com/door43/translationstudio/newui/home/TargetTranslationInfoDialog.java, app/src/main/java/com/door43/translationstudio/newui/newtranslation/NewTargetTranslationActivity.java, app/src/main/res/layout/dialog_target_translation_info.xml, app/src/main/res/values/strings.xml
Fixes #1319 Allow users to change the target language of their translation 
- changed NewTargetTranslationActivity to accept parameters to select and change target language.
=> Fix #1319 Allow users to change the target language of their translation

app/src/main/res/values/strings.xml
Fix #1605 modify upload conflicting project dialog
- Added missing "changes" in merge prompt.
=> Fix QA fail #1605 modify upload conflicting project dialog

app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java
Fix #1255 QA fail add interface for handling merge conflicts
-Fix for setting font sizes on merge conflicts to address inconsistent sizing.
@neutrinog - ready to send to QA for review.
=> Fix QA fail #1255 add interface for handling merge conflicts - inconsistent font sizes

app/src/androidTest/java/com/door43/translationstudio/ui/newlanguage/NewLanguageActivityUiUtils.java, app/src/androidTest/java/com/door43/translationstudio/ui/newlanguage/QuestionnaireActivityUiTest.java
Fix #1588 fix new language questions test
- Fixing Espresso test for new languages questions.
=> Fix #1588 fix new language questions test

app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java
Fix #1675 crash on new project
- fixed invalid cast.
=> Fix #1675 crash on new project

app/src/main/java/com/door43/translationstudio/core/TargetTranslation.java
Fix #1683 crash changing fonts
- Added cleanup of redundant source translations.  Saw problem with old projects having thousands of duplicate sources.
=> Fix #1683 crash changing fonts

app/src/main/java/com/door43/translationstudio/core/ExportUsfm.java, app/src/main/java/com/door43/translationstudio/core/ImportUsfm.java, app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java, app/src/main/java/com/door43/translationstudio/core/Util.java, app/src/main/java/com/door43/translationstudio/tasks/PrintPDFTask.java, app/src/main/java/com/door43/translationstudio/tasks/UpdateAllTask.java, app/src/main/java/com/door43/translationstudio/tasks/UpdateCatalogsTask.java, app/src/main/java/com/door43/translationstudio/tasks/UpdateSourceTask.java, app/src/main/java/com/door43/translationstudio/ui/dialogs/PrintDialog.java, app/src/main/java/com/door43/translationstudio/ui/filechooser/FileChooserActivity.java, app/src/main/java/com/door43/translationstudio/ui/home/HomeActivity.java, app/src/main/java/com/door43/translationstudio/ui/translate/ChooseSourceTranslationAdapter.java, app/src/main/java/com/door43/translationstudio/ui/translate/ChooseSourceTranslationDialog.java, app/src/main/java/com/door43/translationstudio/ui/translate/FirstTabFragment.java, app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java, app/src/main/java/com/door43/translationstudio/ui/translate/ViewModeFragment.java, app/src/main/java/com/door43/util/Manifest.java, app/src/main/res/layout/dialog_choose_source_translation.xml, app/src/main/res/layout/dialog_update_library.xml, app/src/main/res/layout/fragment_pdf_output_filename.xml, app/src/main/res/values/strings.xml
Fix #1694 modify project source language selection dialog
- Updated dialog to match UI design - added new section for available to download.
=> Fix 1694 modify project source language selection dialog

app/src/main/java/com/door43/translationstudio/ui/translate/ChunkModeAdapter.java, app/src/main/java/com/door43/translationstudio/ui/translate/ReadModeAdapter.java, app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java
Fix QA fail of #1549: force font redraw
- update displayed text fonts when new font selected.
=> Fix QA fail of #1549: force font redraw

app/src/main/java/com/door43/translationstudio/ui/translate/ListItem.java, app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java
Fix #1705 verse marker oddities
- Fixed missing verse markers.
=> Fix #1705 verse marker oddities

app/src/androidTest/java/com/door43/translationstudio/core/MergeConflictsParseTaskTest.java, app/src/main/java/com/door43/translationstudio/core/MergeConflictsHandler.java, app/src/main/java/com/door43/translationstudio/core/Typography.java, app/src/main/java/com/door43/translationstudio/tasks/MergeConflictsParseTask.java, app/src/main/java/com/door43/translationstudio/tasks/ValidationTask.java, app/src/main/java/com/door43/translationstudio/ui/dialogs/BackupDialog.java, app/src/main/java/com/door43/translationstudio/ui/dialogs/ShareWithPeerDialog.java, app/src/main/java/com/door43/translationstudio/ui/home/HomeActivity.java, app/src/main/java/com/door43/translationstudio/ui/home/ImportDialog.java, app/src/main/java/com/door43/translationstudio/ui/home/ImportFromDoor43Dialog.java, app/src/main/java/com/door43/translationstudio/ui/newtranslation/NewTargetTranslationActivity.java, app/src/main/java/com/door43/translationstudio/ui/translate/ListItem.java, app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java
Fix #1290 QA fail - UI for merge conflicts
- Added verification of translation merge conflict to address issue that sometimes the merge conflict may not be in an editable chunk, but may be in manifest.
- separated merge conflict code out to MergeConflictsHandler.
- Added fix for case that merge conflict may be in title.
=> Fix #1290 QA fail - UI for merge conflicts

app/src/main/java/com/door43/translationstudio/ui/SettingsActivity.java, app/src/main/java/com/door43/translationstudio/ui/home/HomeActivity.java, app/src/main/java/com/door43/translationstudio/ui/home/UpdateLibraryDialog.java, app/src/main/res/layout/dialog_update_library.xml, app/src/main/res/values/strings.xml
Fix #1690 modify update options prompt
- Updated options menu to add check for updated app.
- Added info button to Updated options menu that opens browser to help page.
- Hid the option to view new and updated sources - not yet implemented.
=> Fix #1690 modify update options prompt

app/src/main/java/com/door43/translationstudio/ui/translate/ChooseSourceTranslationAdapter.java, app/src/main/java/com/door43/translationstudio/ui/translate/ChooseSourceTranslationDialog.java, app/src/main/res/values/strings.xml
Fix #1700 add language search to ChooseSourceTranslationDialog
=> Fix 1700 add language search to ChooseSourceTranslationDialog

app/src/main/java/com/door43/translationstudio/ui/home/TargetTranslationAdapter.java, app/src/main/java/com/door43/translationstudio/ui/home/TargetTranslationListFragment.java, app/src/main/res/layout-port/fragment_target_translation_list.xml, app/src/main/res/layout-sw600dp-port/fragment_target_translation_list.xml, app/src/main/res/layout-sw600dp/fragment_target_translation_list.xml, app/src/main/res/layout/fragment_target_translation_list.xml, app/src/main/res/values/strings.xml
Fixes #1593 Provide sort options for project list.
- modified TargetTranslationAdapter and TargetTranslationListFragment to support sorting.
- modified all versions of fragment_target_translation_list.xml to add sort controls.
=> Fixes #1593 Provide sort options for project list.

app/src/androidTest/java/com/door43/translationstudio/core/ExportUsfmTest.java, app/src/main/java/com/door43/translationstudio/ui/dialogs/BackupDialog.java
Fix QA fail #1636 export USFM to any folder
- Fixed logic error that export USFM would sometimes try to save to SD card even through internal file system was selected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1750)
=> Fix QA fail #1636 export USFM to any folder

app/src/main/java/com/door43/translationstudio/ui/ProfileActivity.java, app/src/main/java/com/door43/translationstudio/ui/dialogs/BackupDialog.java, app/src/main/java/com/door43/translationstudio/ui/home/HomeActivity.java, app/src/main/res/layout-port/activity_home.xml, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/dialog_backup.xml, app/src/main/res/values/strings.xml
Fix #1641 Add visual indication of current logged in user
- Added current user indication to home screen.
- Added current user indication to upload dialog.
@neutrinog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1754)
=> Fix #1641 Add visual indication of current logged in user

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java, app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java, app/src/main/java/com/door43/translationstudio/ui/translate/TranslationFilter.java
Fix #1652 qa fail navigation fix
- Change search next and previous to move by whole chunks. 
- Fix to apply ChangedText() to check for null string.
- Change to Preserve last search type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1783)
=> Fix #1652 QA fail - navigation fix

app/src/main/java/com/door43/translationstudio/ui/newtranslation/NewTargetTranslationActivity.java
Fix #1319 change target language with conflict
- Fixed problem with how we detect merge conflicts on language changes.  Removed hard coded resource slugs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1791)
=> Fix #1319 QA Fail - change target language with conflict

app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java
Fix #1805 & #1640 print fails on usfm import
- PdfPrinter - Fix for chapter 0 with id of front.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1811)
=> Fix #1805 & #1640 print fails on usfm import

app/src/main/java/com/door43/translationstudio/ui/translate/ViewModeFragment.java
Fixes #1804 blank screen displayed
- Added progress dialog while sources are being loaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1856)
=> Fixes #1804 blank screen displayed

app/src/main/java/com/door43/translationstudio/tasks/GetAvailableSourcesTask.java, app/src/main/java/com/door43/translationstudio/ui/dialogs/DownloadSourcesAdapter.java
Fix #1773 disable update of TA since future changes could break the app.
- Disabled updating of TA since a major change coming up could break the app.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1869)
=> Fix #1773 disable update of TA since future changes could break the app.

app/src/main/res/values/strings.xml
Fix #1777 QA Fail - fix verbiage on upload dialog
- fix verbiage on upload dialog tips.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1890)
=> Fix #1777 QA Fail - fix verbiage on upload dialog

app/src/main/java/com/door43/translationstudio/ui/translate/ViewModeFragment.java
Fix #1897 project resets to top of page on source change
- ViewModeAdapter - Save scroll position before changing source and then restore after source changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1908)
=> Fix #1897 project resets to top of page on source change

app/build.gradle
bumped build number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1943)
=> bumped build number.

app/src/main/java/com/door43/translationstudio/tasks/ValidationTask.java
Fix #1932 QA extra book summary card at end
- ValidationTask - sorted chapters, so "front" is first.  Removed special handling for "front" chapter since it is handled automatically like any other chapter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1964)
=> Fix #1932 QA extra book summary card at end

app/build.gradle, app/src/main/java/com/door43/translationstudio/tasks/DownloadResourceContainersTask.java, app/src/main/java/com/door43/translationstudio/ui/dialogs/DownloadSourcesDialog.java
Fix #2004 download stuck
- DownloadResourceContainersTask - improved exception logging for later debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2008)
=> Fix #2004 download stuck

app/build.gradle
Fix #2004 download stuck recovery
- Uses updated client library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2015)
=> Fix #2004 download stuck recovery

app/src/main/java/com/door43/translationstudio/ui/home/TargetTranslationAdapter.java
Fixes #2003 crash on wakeup
- TargetTranslationAdapter - in setProgress(), added sanity checking to progress bar range.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2013)
=> Fixes #2003 crash on wakeup

app/src/main/res/values/strings.xml
Fix #1638 QA Fail - text cleanup SD card prompt
- Fix text on SD card prompt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2031)
=> Fix #1638 QA Fail - text cleanup SD card prompt

app/src/main/java/com/door43/translationstudio/ui/translate/ChooseSourceTranslationDialog.java
Fix #2024 resource not found on import
- ChooseSourceTranslationDialog - fixed error if resource not found.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2033)
=> Fix #2024 resource not found on import

app/src/main/java/com/door43/translationstudio/ui/newtranslation/NewTargetTranslationActivity.java, app/src/main/res/layout-port/toolbar_translator_sidebar.xml
Fix #2028 crash trying to create new project
- NewTargetTranslationActivity - Fix exception thrown creating new translation when default english resource does not exist.
- toolbar_translator_sidebar.xml - Fixed missing merge conflict indicator in layout-port
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2038)
=> Fix #2028 crash trying to create new project

app/src/main/res/values/strings.xml
Fix #1638 QA Fail - clean up SD card prompt
- Clean up text for SD card prompt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2044)
=> Fix #1638 QA Fail - clean up SD card prompt

app/src/main/res/layout-sw600dp/dialog_import_from_door43.xml, app/src/main/res/layout-sw600dp/fragment_restore_from_cloud_list_item.xml
Fixes #2037 - QA fail on phone screen size
- Customized small screen layout for import from door 43 dialog.
- Copied original layout files dialog_import_from_door43.xml and fragment_restore_from_cloud_list_item.xml to layout to layout-sw600dp
- Modified the layout files dialog_import_from_door43.xml and fragment_restore_from_cloud_list_item.xml to support small screen sizes.
=> Fixes #2037 - QA fail on phone screen size

app/src/main/java/com/door43/translationstudio/ui/translate/ReviewModeAdapter.java, app/src/main/res/values/strings.xml
Fix #1762 change merge complete dialog
- Changes to text shown on merge complete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2048)
=> Fix 1762 change merge complete dialog

app/src/main/res/values/strings.xml
Fix #2016 update SD card success text
- Changes to text shown on SD card access success.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2052)
=> Fix #2016 update SD card success text

app/src/main/res/values/strings.xml
Fix #1638 text cleanup SD card access
- Changes to text shown on SD card access instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2053)
=> Fix #1638 text cleanup SD card access

app/build.gradle
Bumped build to 169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2071)
=> Bumped build to 169

app/build.gradle, app/src/main/java/com/door43/translationstudio/ui/home/TranslationRepositoryAdapter.java
Fix #2061 search abnormalities door43
- TranslationRepositoryAdapter - fixed to make sure we trigger redraw even if there are no items in list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2072)
=> Fix #2061 search abnormalities door43

app/build.gradle, app/src/main/java/com/door43/translationstudio/App.java, app/src/main/java/com/door43/translationstudio/ui/SplashScreenActivity.java, app/src/main/java/com/door43/translationstudio/ui/devtools/DeveloperToolsActivity.java
Fix #2067 low resources verification
- DeveloperToolsActivity - added new item to display system resources and troubleshooting information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2089)
=>  Fix #2067 low resources verification

app/src/main/java/com/door43/translationstudio/ui/home/TargetTranslationInfoDialog.java, app/src/main/java/com/door43/translationstudio/ui/home/TranslationRepositoryAdapter.java
Fix #2133 more language font fixes
- TranslationRepositoryAdapter - Fixed Typeface on title.	
- TargetTranslationInfoDialog - Fixed Typeface on title and language title.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2137)
=> Fix #2133 more language font fixes

app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java
Fix #2155 chapter titles
- PdfPrinter - Use font when adding chapter title to toc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2160)
=> Fix #2155 chapter titles

app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java
Fix #2156 QA fail - fix print RTL
fix broken merge.
- updated itextpdf to version 5.5.10
- PdfPrinter, PrintPDFTask - Added progress update for each chapter. This is helpful since printing now takes longer with all the added tables with RTL support.
- PdfPrinter - Putting chapter chunks, Title Page, TOC and chapter title in table and enabling BIDI (RTL and LTR).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2165)
=> Fix #2156 QA fail - fix print RTL

app/src/main/java/com/door43/translationstudio/core/PdfPrinter.java
Fix #2156 QA fail - print RTL
- PdfPrinter - fix image printing. Fix printing wide TOC with wide chapter titles.
- PdfPrinter - tweak progress counting to show increment after TOC table generated and first chapter begun.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2167)
=> Fix #2156 QA fail - print RTL

app/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/ts-android/2368)
=> Updated statement of faith, includes creeds and references
